.PHONY: clean All

All:
	@echo "----------Building project:[ PrimitiveDataType - Debug ]----------"
	@cd "DecimaltoBit" && "$(MAKE)" -f  "PrimitiveDataType.mk"
clean:
	@echo "----------Cleaning project:[ PrimitiveDataType - Debug ]----------"
	@cd "DecimaltoBit" && "$(MAKE)" -f  "PrimitiveDataType.mk" clean
