.PHONY: clean All

All:
	@echo "----------Building project:[ IncludePreProcessorDirective - Debug ]----------"
	@cd "IncludePreProcessorDirective" && "$(MAKE)" -f  "IncludePreProcessorDirective.mk"
clean:
	@echo "----------Cleaning project:[ IncludePreProcessorDirective - Debug ]----------"
	@cd "IncludePreProcessorDirective" && "$(MAKE)" -f  "IncludePreProcessorDirective.mk" clean
