.PHONY: clean All

All:
	@echo "----------Building project:[ References1 - Debug ]----------"
	@cd "References" && "$(MAKE)" -f  "References1.mk"
clean:
	@echo "----------Cleaning project:[ References1 - Debug ]----------"
	@cd "References" && "$(MAKE)" -f  "References1.mk" clean
