.PHONY: clean All

All:
	@echo "----------Building project:[ References2 - Debug ]----------"
	@cd "References2" && "$(MAKE)" -f  "References2.mk"
clean:
	@echo "----------Cleaning project:[ References2 - Debug ]----------"
	@cd "References2" && "$(MAKE)" -f  "References2.mk" clean
