.PHONY: clean All

All:
	@echo "==========Building project:[ PreVirtualFunctions - Debug ]=========="
	@cd "PreVirtualFunctions" && "$(MAKE)" -f  "PreVirtualFunctions.mk"
clean:
	@echo "==========Cleaning project:[ PreVirtualFunctions - Debug ]----------"
	@cd "PreVirtualFunctions" && "$(MAKE)" -f  "PreVirtualFunctions.mk" clean
