.PHONY: clean All

All:
	@echo "----------Building project:[ CodeChallenge - Debug ]----------"
	@cd "CodeChallenge" && "$(MAKE)" -f  "CodeChallenge.mk"
clean:
	@echo "----------Cleaning project:[ CodeChallenge - Debug ]----------"
	@cd "CodeChallenge" && "$(MAKE)" -f  "CodeChallenge.mk" clean
