.PHONY: clean All

All:
	@echo "==========Building project:[ Mystring-insertion-extraction -  ]=========="
	@cd "Mystring-insertion-extraction" && "$(MAKE)" -f  "Mystring-insertion-extraction.mk"
clean:
	@echo "==========Cleaning project:[ Mystring-insertion-extraction -  ]----------"
	@cd "Mystring-insertion-extraction" && "$(MAKE)" -f  "Mystring-insertion-extraction.mk" clean
