.PHONY: clean All

All:
	@echo "----------Building project:[ ConstinClasses - Debug ]----------"
	@cd "ConstinClasses" && "$(MAKE)" -f  "ConstinClasses.mk"
clean:
	@echo "----------Cleaning project:[ ConstinClasses - Debug ]----------"
	@cd "ConstinClasses" && "$(MAKE)" -f  "ConstinClasses.mk" clean
