.PHONY: clean All

All:
	@echo "----------Building project:[ DafaultConstructor - Debug ]----------"
	@cd "DafaultConstructor" && "$(MAKE)" -f  "DafaultConstructor.mk"
clean:
	@echo "----------Cleaning project:[ DafaultConstructor - Debug ]----------"
	@cd "DafaultConstructor" && "$(MAKE)" -f  "DafaultConstructor.mk" clean
