.PHONY: clean All

All:
	@echo "==========Building project:[ DerivingOurFistClass - Debug ]=========="
	@cd "DerivingOurFistClass" && "$(MAKE)" -f  "DerivingOurFistClass.mk"
clean:
	@echo "==========Cleaning project:[ DerivingOurFistClass - Debug ]----------"
	@cd "DerivingOurFistClass" && "$(MAKE)" -f  "DerivingOurFistClass.mk" clean
