.PHONY: clean All

All:
	@echo "==========Building project:[ CopyCOnstructorAssignmentOperator - Debug ]=========="
	@cd "CopyCOnstructorAssignmentOperator" && "$(MAKE)" -f  "CopyCOnstructorAssignmentOperator.mk"
clean:
	@echo "==========Cleaning project:[ CopyCOnstructorAssignmentOperator - Debug ]----------"
	@cd "CopyCOnstructorAssignmentOperator" && "$(MAKE)" -f  "CopyCOnstructorAssignmentOperator.mk" clean
