.PHONY: clean All

All:
	@echo "----------Building project:[ BilateralFilter - Debug ]----------"
	@cd "BilateralFilter" && "$(MAKE)" -f  "BilateralFilter.mk"
clean:
	@echo "----------Cleaning project:[ BilateralFilter - Debug ]----------"
	@cd "BilateralFilter" && "$(MAKE)" -f  "BilateralFilter.mk" clean
