.PHONY: clean All

All:
	@echo "----------Building project:[ FunctinoOverloading - Debug ]----------"
	@cd "FunctinoOverloading" && "$(MAKE)" -f  "FunctinoOverloading.mk"
clean:
	@echo "----------Cleaning project:[ FunctinoOverloading - Debug ]----------"
	@cd "FunctinoOverloading" && "$(MAKE)" -f  "FunctinoOverloading.mk" clean
